/* rest_aes.c
 * Compiled with clang, calls subbytes_kernel generated by veclangc
 * Verifies result matches baseline and performs simple timing
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>

/* AES standard S-box, converted to int type */
static const int AES_SBOX[256] = {
  99,124,119,123,242,107,111,197, 48,  1,103, 43,254,215,171,118,
  202,130,201,125,250, 89, 71,240,173,212,162,175,156,164,114,192,
  183,253,147, 38, 54, 63,247,204, 52,165,229,241,113,216, 49, 21,
   4,199, 35,195, 24,150,  5,154,  7, 18,128,226,235, 39,178,117,
   9,131, 44, 26, 27,110, 90,160, 82, 59,214,179, 41,227, 47,132,
  83,209,  0,237, 32,252,177, 91,106,203,190, 57, 74, 76, 88,207,
  208,239,170,251, 67, 77, 51,133, 69,249,  2,127, 80, 60,159,168,
  81,163, 64,143,146,157, 56,245,188,182,218, 33, 16,255,243,210,
  205, 12, 19,236, 95,151, 68, 23,196,167,126, 61,100, 93, 25,115,
   96,129, 79,220, 34, 42,144,136, 70,238,184, 20,222, 94, 11,219,
  224, 50, 58, 10, 73,  6, 36, 92,194,211,172, 98,145,149,228,121,
  231,200, 55,109,141,213, 78,169,108, 86,244,234,101,122,174,  8,
  186,120, 37, 46, 28,166,180,198,232,221,116, 31, 75,189,139,138,
  112, 62,181,102, 72,  3,246, 14, 97, 53, 87,185,134,193, 29,158,
  225,248,152, 17,105,217,142,148,155, 30,135,233,206, 85, 40,223,
  140,161,137, 13,191,230, 66,104, 65,153, 45, 15,176, 84,187, 22
};

/* Function generated by veclangc (provided by linker) */
int subbytes_kernel(const int* sbox, const int* in, int* out, int n);

/* baseline: pure clang table lookup */
static void subbytes_clang(const int* sbox, const uint8_t* in, uint8_t* out, int n) {
    for (int i = 0; i < n; i++) {
        out[i] = (uint8_t)sbox[in[i]];
    }
}

/* Simple timing */
static double now_sec(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}

int main(int argc, char** argv) {
    int n = (argc > 1 ? atoi(argv[1]) : 1<<20); // default 1M
    uint8_t* in   = (uint8_t*)malloc(n);
    uint8_t* out1 = (uint8_t*)malloc(n);
    uint8_t* out2 = (uint8_t*)malloc(n);
    int* tmp_in   = (int*)malloc(sizeof(int) * n);
    int* tmp_out  = (int*)malloc(sizeof(int) * n);

    if (!in || !out1 || !out2 || !tmp_in || !tmp_out) {
        perror("malloc");
        return 2;
    }

    for (int i = 0; i < n; i++) in[i] = (uint8_t)(i * 1315423911u);

    double t0 = now_sec();
    subbytes_clang(AES_SBOX, in, out1, n);
    double t1 = now_sec();

    for (int i = 0; i < n; i++) tmp_in[i] = (int)in[i];
    double t2 = now_sec();
    subbytes_kernel(AES_SBOX, tmp_in, tmp_out, n);
    double t3 = now_sec();
    for (int i = 0; i < n; i++) out2[i] = (uint8_t)tmp_out[i];

    for (int i = 0; i < n; i++) {
        if (out1[i] != out2[i]) {
            fprintf(stderr, "mismatch at %d: %u vs %u\n", i, (unsigned)out1[i], (unsigned)out2[i]);
            return 3;
        }
    }

    printf("OK n=%d  clang=%.3fs  veclangc=%.3fs\n", n, t1 - t0, t3 - t2);

    free(in); free(out1); free(out2); free(tmp_in); free(tmp_out);
    return 0;
}
